version: "3"

services:
  webserver:
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./htdocs/:/var/www/html/
    expose:
      - 80
    ports:
      - "8100:80"
    stdin_open: true
    tty: true

  db:
    image: mysql:5.7
    container_name: db-mysql
    environment:
      - MYSQL_DATABASE=sa
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
    ports:
      - 9906:3306
    volumes: 
    - ./mysql:/var/lib/mysql